version: '3.4'

services:
  patronage.api:
    build:
      context: .
      dockerfile: src/Patronage.Api/Dockerfile
    image: papuzkas/patronageapi
    ports:
      - "5000:80"
    environment:
      - COMPOSE_TLS_VERSION= "TLSv1_2"
    volumes:
      - ./logs:/src/logs
    depends_on:
      - database
  database:
    build: ./src/Patronage.Api/mssql
    image: papuzkas/patronage_database
    environment:
     ACCEPT_EULA: "Y"
     SA_PASSWORD: "Pwd12345"
     MSSQL_DB: "patronageDB"
     MSSQL_USER: "user1"
     MSSQL_PASSWORD: "Pwd12345"
    ports:
     - "1433:1433"
    volumes:
      - ./mssql/data:/var/opt/mssql/data