version: '3.4'

services:
  patronage.api:
    image: ${DOCKER_REGISTRY-}patronageapi
    build:
      context: .
      dockerfile: src/Patronage.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - COMPOSE_TLS_VERSION= "TLSv1_2"