# Your workflow name.
name: Run tests and deploy to heroku.

# Run workflow on every push to master branch.
on:
  push:
    branches: [master]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore patronage22-dotnet-bialystok.sln
      - name: Build
        run: dotnet build patronage22-dotnet-bialystok.sln --no-restore --configuration Release
      - name: Test
        run: dotnet test /home/runner/work/patronage22-dotnet-bialystok/patronage22-dotnet-bialystok/src/Patronage.Tests/bin/Release/net6.0/Patronage.Tests.dll --no-build --verbosity normal
      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_MAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "patronageapi"
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
